terms:
  - id: British Library
    term: British Library
    active: true
  - id: British Museum
    term: British Museum
    active: true
  - id: MOLA
    term: MOLA
    active: true
    #  National Museums of Scotland has to be kept as `active: false` (i.e. not to display/chose from)
    #  else any record already saved with one of them will throw an error
  - id: National Museums of Scotland
    term: National Museums of Scotland
    active: false
  - id: National Museums Scotland
    term: National Museums Scotland
    active: true
  - id: Royal Botanic Gardens, Kew
    term: Royal Botanic Gardens, Kew
    active: true
  - id: Tate
    term: Tate
    active: true
  - id: Barts Health NHS Trust
    term: Barts Health NHS Trust
    active: true
  - id: Black Country Health Libraries Consortium
    term: Black Country Health Libraries Consortium
    active: true
  - id: Birmingham and Solihull Mental Health NHS Foundation Trust
    term: Birmingham and Solihull Mental Health NHS Foundation Trust
    active: true
  - id: Gloucestershire Hospitals NHS Foundation Trust
    term: Gloucestershire Hospitals NHS Foundation Trust
    active: true
  - id: Norfolk and Waveney Strategic Transformation Partnership
    term: Norfolk and Waveney Strategic Transformation Partnership
    active: true
  - id: Somerset NHS Foundation Trust
    term: Somerset NHS Foundation Trust
    active: true
